version: '3'
services:
  varfolomeevamv-netology-prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - varfolomeevamv-my-netology-hw
    restart: always

  varfolomeevamv-netology-pushgateway:
    depends_on: ["varfolomeevamv-netology-prometheus"]
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - varfolomeevamv-my-netology-hw
    restart: unless-stopped

  varfolomeevamv-netology-grafana:
    depends_on: ["varfolomeevamv-netology-pushgateway"] 
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./custom.ini:/etc/grafana/custom.ini
      - grafana_data:/var/lib/grafana
    networks:
      - varfolomeevamv-my-netology-hw
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {} 

networks:
  varfolomeevamv-my-netology-hw:
    driver: bridge
    ipam:
     config:
       - subnet: "10.5.0.0/16"
         gateway: "10.5.0.1"
